# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f1e8ad0ad6de6000d29d860663458910f964e9a23ef10d83c16f8269504c27c708378ab94e0c99e2966768c0346c36b28451cdc4432b5bfcfd22d6e2a22fe7

test:
  secret_key_base: b1c90a6c02c4a8f5f9122f0c96753156bd531fc94326763696eabafca06c192c0880eeefca976c4f30033901c2676680959b0b5e66e2ad42125520f5f33fa72f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
